# Generated by Django 2.1.4 on 2018-12-16 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empl_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
