# Generated by Django 2.1.4 on 2018-12-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20181216_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='superviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
