# Generated by Django 2.1.4 on 2018-12-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20181216_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=300),
        ),
    ]
