# Generated by Django 2.1.4 on 2018-12-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='patronymic',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='surname',
            new_name='middle_name',
        ),
    ]
