# Generated by Django 2.1.4 on 2018-12-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20181223_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(max_length=10),
        ),
    ]
